-- 코드를 입력하세요
SELECT YEAR(s.SALES_DATE) YEAR, MONTH(s.SALES_DATE) MONTH, u.GENDER, COUNT(DISTINCT (u.USER_ID)) USERS
FROM ONLINE_SALE s
JOIN USER_INFO u ON s.USER_ID = u.USER_ID
WHERE u.GENDER IS NOT NULL
GROUP BY YEAR, MONTH, GENDER
ORDER BY YEAR, MONTH, GENDER, USERS