-- 코드를 입력하세요
WITH RECURSIVE HOURS AS (
    SELECT 0 AS HOUR
    UNION ALL
    SELECT HOUR + 1
    FROM HOURS
    WHERE HOUR < 23
)

SELECT h.HOUR, COUNT(a.ANIMAL_ID) AS COUNT
FROM HOURS h
LEFT JOIN ANIMAL_OUTS a ON HOUR(a.DATETIME) = h.HOUR
GROUP BY h.HOUR
ORDER BY h.HOUR;