-- 코드를 작성해주세요
SELECT c.ITEM_ID, c.ITEM_NAME, c.RARITY
FROM ITEM_INFO as p
JOIN ITEM_TREE as t ON t.PARENT_ITEM_ID = p.ITEM_ID
JOIN ITEM_INFO as c ON c.ITEM_ID = t.ITEM_ID
WHERE p.RARITY = 'RARE'
ORDER BY c.ITEM_ID DESC;