-- 코드를 입력하세요
SELECT b.CATEGORY, SUM(s.SALES) TOTAL_SALES
FROM BOOK b
JOIN BOOK_SALES s ON b.BOOK_ID = s.BOOK_ID
WHERE YEAR(s.SALES_DATE) = '2022' AND MONTH(s.SALES_DATE)  = '01'
GROUP BY CATEGORY
ORDER BY CATEGORY