-- 코드를 입력하세요
SELECT CATEGORY, PRICE AS MAX_PRICE, PRODUCT_NAME
FROM FOOD_PRODUCT
WHERE CATEGORY IN ('식용유', '과자', '국', '김치')
    AND PRICE = (
        SELECT MAX(PRICE)
        FROM FOOD_PRODUCT F2
        WHERE F2.CATEGORY = FOOD_PRODUCT.CATEGORY
    )
ORDER BY MAX_PRICE DESC;