-- 코드를 작성해주세요
SELECT 
    CASE
        WHEN SUM(CASE WHEN S.CATEGORY = 'Front End' THEN 1 ELSE 0 END) > 0
            AND SUM(CASE WHEN S.NAME = 'Python' THEN 1 ELSE 0 END) > 0
        THEN 'A'
        WHEN SUM(CASE WHEN S.NAME = 'C#' THEN 1 ELSE 0 END) > 0
        THEN 'B'
        WHEN SUM(CASE WHEN S.CATEGORY = 'Front End' THEN 1 ELSE 0 END) > 0
        THEN 'C'
        END AS GRADE,
        D.ID, D.EMAIL
FROM DEVELOPERS D
JOIN SKILLCODES S ON (D.SKILL_CODE & S.CODE) <> 0
GROUP BY D.ID, D.EMAIL
HAVING GRADE IS NOT NULL
ORDER BY GRADE, D.ID;